services:
  seumanoel.api:
    image: seumanoel.api
    build:
      context: .
      dockerfile: SeuManoel.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - db
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Senha@123
      - ACCEPT_EULA=Y
